### ISSUE TITLE
Postgres image pull failing: manifest not found

### ISSUE THREAD

**Issue by dcupif** [unixelias/docker-dspace#14] opened 2017-12-23 09:09 UTC
Hi,

I pulled your docker-dspace image and then tried to pull and run your custom postgres image. It fails with:

`$ docker run -d --name dspace_db -p 5432:5432 unixelias/postgres-dspace
Unable to find image 'unixelias/postgres-dspace:latest' locally
docker: Error response from daemon: manifest for unixelias/postgres-dspace:latest not found.
See 'docker run --help'.
`

Is it possible to just use another regular image? I don't need the locale to be changed.

Thank you for this dspace image, I think this is going to save me a lot of time!

**Comment by unixelias** [comment] 2017-12-23 16:10
Thanks for the report.

So, I think the problem is that I don't have the 'latest' tag on Docker Hub, but you can use the '9.6-ptbr' tag. However, you  don't need to use only my custom image. As you could see, the only change I made from the library version is the local change, thus I suggest you to use the default postgres from docker library.

By the way, next week I will fix this error and change the use of the postgres image, beacouse recently I taked a look into the docker postgres library and I have found this: 

-*-
You can also extend the image with a simple Dockerfile to set a different locale. The following example will set the default locale to de_DE.utf8:

FROM postgres:9.4
RUN localedef -i de_DE -c -f UTF-8 -A /usr/share/locale/locale.alias de_DE.UTF-8
ENV LANG de_DE.utf8

Since database initialization only happens on container startup, this allows us to set the language before it is created.

-*-

It's good to know that my work can help you. Feel free to ask help if you need.

**Comment by dcupif** [comment] 2018-01-02 16:13
Thanks for your answer.

I tried with the official postgres image and went through the automatic build. However, DSpace shows an internal system error on the home page (jspui webapp).

I am not familiar at all with Docker. and I am not confident how I can access DSpace logs to track the problem. Could you please point me in the right direction?

Happy new year :)

**Comment by unixelias** [comment] 2018-01-05 04:17
Hello Damien,

I also have had this kind of error on the jspui and I think it's because of the default language collation. By the way I've created another tag with english as default language and I pointed the 'latest' tag to this en_US version. If the build process succeds you can try the new version.

It is also possible (maybe) to find some new erros due to the new version of Dspace (6.2), so please take a look and let me know if it works fine.

I wish you a happy new year too

**Comment by unixelias** [comment] 2018-01-05 12:56
About he logs: you can access the logs starting the Stack without use the daemon as:
`docker-compose up`
This way you will receive the logs in real time.
Another way to do is using the docker logs command as:
`docker logs <ID or Name>`

I also suggest Docker's official documentation, which was very useful to me. I think it is a very long text, although it is detailed and well explained, so it is possible to find good explanations about commands and examples of use.

Logs from Docker: https://docs.docker.com/engine/reference/commandline/logs/

Logs from docker-compose: https://docs.docker.com/compose/reference/logs/

You can also go inside the container: https://docs.docker.com/engine/reference/commandline/exec/

**Comment by unixelias** [comment] 2018-04-05 23:03
I'm closing it for now, but if you want something else, please e-mail me.

**Closed as completed by unixelias** 2018-04-05 23:03 UTC
